CREATE TABLE CONFIG (
C_ID   NUMERIC PRIMARY KEY NOT NULL,
C_NAME VARCHAR NOT NULL,
C_TYPE VARCHAR NOT NULL,
C_VALUE VARCHAR NOT NULL 
);

CREATE TABLE LESSON_GROUP (
LG_ID   NUMERIC PRIMARY KEY NOT NULL,
LG_NAME VARCHAR UNIQUE
);

CREATE TABLE "LESSON" 
(
L_ID   NUMERIC PRIMARY KEY NOT NULL,
L_LG_ID   NUMERIC NOT NULL,
L_NAME VARCHAR UNIQUE,
L_CHECK_TIME DATETIME,
L_TOTAL_COUNT   NUMERIC DEFAULT 0,
L_CORRECT_COUNT NUMERIC DEFAULT 0,
FOREIGN KEY (L_LG_ID) REFERENCES LESSON_GROUP (LG_ID) ON DELETE CASCADE
);

CREATE TABLE WORD (
W_ID              NUMERIC PRIMARY KEY NOT NULL,
W_LANGUAGE        VARCHAR NOT NULL, 
W_TEXT            VARCHAR NOT NULL,
W_CORRECT_COUNT   INTEGER DEFAULT 0,
W_INCORRECT_COUNT INTEGER DEFAULT 0,
W_CORRECT_TIME    DATETIME,
W_INCORRECT_TIME  DATETIME
);

CREATE UNIQUE INDEX WORD_UI_WORD_LANG on WORD (W_LANGUAGE,W_TEXT);

CREATE TABLE WORD_GROUP (
WG_ID     NUMERIC PRIMARY KEY NOT NULL, 
WG_L_ID   NUMERIC NOT NULL, 
WG_W1_ID  NUMERIC NOT NULL, 
WG_W2_ID  NUMERIC NOT NULL,
FOREIGN KEY (WG_L_ID) REFERENCES LESSON (L_ID) ON DELETE CASCADE,
FOREIGN KEY (WG_W1_ID) REFERENCES WORD (W_ID),
FOREIGN KEY (WG_W2_ID) REFERENCES WORD (W_ID)
);

CREATE TABLE LESSON_CHECK 
(
LC_ID            NUMERIC PRIMARY KEY NOT NULL,
LC_L_ID          NUMERIC NOT NULL, 
LC_TIME          DATETIME NOT NULL, 
LC_TOTAL_COUNT   INTEGER DEFAULT 0, 
LC_CORRECT_COUNT INTEGER DEFAULT 0,
LC_DURATION      NUMERIC,
FOREIGN KEY (LC_L_ID) REFERENCES LESSON (L_ID) ON DELETE CASCADE 
);

CREATE VIEW total_view (
    t_name,
    t_count
)
AS
    SELECT l_name,
           count(DISTINCT (wg.wg_w1_id) ) 
      FROM LESSON l
           INNER JOIN
           WORD_GROUP wg ON l.l_id = wg.wg_l_id
     GROUP BY l_name
     ORDER BY l_name;
